image: openjdk:8-jdk 

cache:
  paths:
    - .m2/
    - .gradle/

variables:
  ANDROID_COMPILE_SDK: "31"
  ANDROID_BUILD_TOOLS: "31.0.3"
  ANDROID_SDK_TOOLS: "7562133"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./deskBuddyApp/gradlew
    # use yes to accept all licenses
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./deskBuddyApp/gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./deskBuddyApp/gradlew test

