#Specify docker image
image: openjdk:8-jdk 

#Declare variables that are used in the pipeline, in this project's case API 33
variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"
  ANDROID_SDK_TOOLS:   "7583922"

#The stages of the CI/CD and it's order
stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building project..."


unit-test:
  stage: test
  script:
    - echo "Running all tests..."
  only:
    - main

integration-test:
  stage: test
  script:
    - echo "Running integration tests..."
  only:
    - branches
  except:
    - main


