stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y openjdk-8-jdk-headless
  - wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
  - unzip gradle-7.0.2-bin.zip
  - export PATH=$PATH:/path/to/gradle-7.0.2/bin

build:
  stage: build
  script:
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - ./gradlew testDebug
