#Specify docker image
image: openjdk:8-jdk 

#Declare variables that are used in the pipeline, in this project's case API 33





 

#The stages of the CI/CD and its order
stages:
  - build
  - test

#LintDebugger job (static code analysis, before it's run), runs in build stage
lintDebug:
  stage: build
  script:
    - ./deskBuddyApp/gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint #Command that runs the lint debugger with gradle wrapper

#AssembleDebugger job, runs in build stage
assembleDebug:
  stage: build
  script:
    - ./deskBuddyApp/gradlew assembleDebug #Command that runs the assembleDebugger with gradle wrapper
  artifacts:
    paths:
    - app/build/outputs/ #Save contents in this directory as artifacts which can be used later

#Debug tests, runs in test stage 
debugTests:
  stage: test
  script:
    - ./deskBuddyApp/gradlew -Pci --console=plain :app:testDebug #Command that runs this job with gradle wrapper
