image: openjdk:8-jdk

before_script:
  - chmod +x ./deskBuddyApp/gradlew
stages:
  - build
cache:
  paths:
    - .deskBuddyApp/gradle/wrapper
    - .deskBuddyApp/gradle/caches
assembleDebug:
  stage: build
  tags: 
    - docker
  script:
    - ./deskBuddyApp/gradlew assembleDebug
    #- cp app/build/outputs/apk/debug/app-debug.apk app-debug.apk
  #artifacts:
    #paths:
      #- app-debug.apk
