image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"
  ANDROID_SDK_TOOLS: "7583922"

stages:
  - build

before_script:
  - choco install -y wget unzip
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - Expand-Archive -Path android-sdk.zip -DestinationPath android-sdk-linux
  - Set-Location -Path android-sdk-linux
  - New-Item -ItemType Directory -Path licenses
  - Set-Content -Path licenses/android-sdk-license -Value "8933bad161af4178b1185d1a37fbf41ea5269c55`nd56f5187479451eabf01fb78af6dfcb131a6481e"
  - Set-Content -Path licenses/android-sdk-preview-license -Value "84831b9409646a918e30573bab4c9c91346d8abd"
  - Set-Variable -Name "ANDROID_HOME" -Value "$PWD"
  - $env:PATH = "$env:PATH;$PWD\platform-tools"

build:
  stage: build
  script:
    - ./gradlew assembleDebug
