image: javiersantos/android-ci:28.0.3
  
before_script:
  - cd /builds/courses/dit113/2023/group-8/desk-buddy/deskBuddyApp/
  - chmod +x ./gradlew
  

stages:
  - build
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
assembleDebug:
  stage: build
  tags: 
    - docker
  script:
    - ./gradlew assembleDebug
    #- cp app/build/outputs/apk/debug/app-debug.apk app-debug.apk
  #artifacts:
    #paths:
      #- app-debug.apk
