image: gradle:latest

variables:
  # Set the JAVA_HOME environment variable to the location of the Java installation
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

