image: openjdk:8-jdk

before_script:
  - chmod +x ./deskBuddyApp/gradlew

stages:
  - setup
  - build

setup:
  stage: setup
  script:
    - mkdir -p /user/.android/
    - touch /user/.android/repositories.cfg

build:
  stage: build
  script:
    - export ANDROID_HOME=/path/to/android/sdk
    - cd /builds/courses/dit113/2023/group-8/desk-buddy/deskBuddyApp/
    - gradlew build
