image: gradle
  
before_script:
  - export ANDROID_HOME=$PWD/android-sdk-linux #Sets the "ANDROID-HOME" environment variable to the path of the Android SDK directory
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/ #Adds the Android platform tools to the system PATH
  - chmod +x ./deskBuddyApp/gradlew
  

stages:
  - build
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
assembleDebug:
  stage: build
  tags: 
    - docker
  script:
    - cd /builds/courses/dit113/2023/group-8/desk-buddy/deskBuddyApp/
    - ./gradlew assembleDebug
    #- cp app/build/outputs/apk/debug/app-debug.apk app-debug.apk
  #artifacts:
    #paths:
      #- app-debug.apk
